-- ============================================
-- Heavy Haul Move Control System - Database Schema
-- ============================================
-- Run this in Supabase SQL Editor to create all tables and RLS policies
-- ============================================

-- Step 1: Drop existing tables if they exist (clean slate for Heavy Haul schema)
-- This removes old schema from FounderOpsAutomation

DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS moves CASCADE;
DROP TABLE IF EXISTS admin_profiles CASCADE;

-- Step 2: Create Tables

-- Moves table
CREATE TABLE moves (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  origin TEXT NOT NULL,
  destination TEXT NOT NULL,
  width NUMERIC NOT NULL,
  height NUMERIC NOT NULL,
  weight NUMERIC NOT NULL,
  states_crossed INTEGER NOT NULL,
  delivery_date DATE NOT NULL,
  permit_status TEXT NOT NULL DEFAULT 'pending',
  escort_status TEXT NOT NULL DEFAULT 'not_scheduled',
  overall_status TEXT NOT NULL DEFAULT 'intake',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Documents table
CREATE TABLE documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  move_id BIGINT REFERENCES moves(id) ON DELETE CASCADE,
  insurance_cert BOOLEAN DEFAULT false,
  rateconfirmation BOOLEAN DEFAULT false,
  bill_of_lading BOOLEAN DEFAULT false,
  escort_confirmation BOOLEAN DEFAULT false,
  route_plan BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Admin profiles table (links to Supabase Auth users)
CREATE TABLE admin_profiles (
  id UUID PRIMARY KEY,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Step 3: Enable Row Level Security

ALTER TABLE moves ENABLE ROW LEVEL SECURITY;
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_profiles ENABLE ROW LEVEL SECURITY;

-- Step 4: Drop any existing policies (clean slate)

DROP POLICY IF EXISTS "public_insert_moves" ON moves;
DROP POLICY IF EXISTS "admin_select_moves" ON moves;
DROP POLICY IF EXISTS "admin_update_moves" ON moves;
DROP POLICY IF EXISTS "service_role_all_moves" ON moves;
DROP POLICY IF EXISTS "public_insert_documents" ON documents;
DROP POLICY IF EXISTS "admin_select_documents" ON documents;
DROP POLICY IF EXISTS "admin_all_documents" ON documents;
DROP POLICY IF EXISTS "service_role_all_documents" ON documents;
DROP POLICY IF EXISTS "admin_users_select_any_admin" ON admin_profiles;

-- Step 5: Grant table permissions for client-side SDK usage

GRANT INSERT, SELECT ON moves TO anon;
GRANT ALL ON moves TO authenticated;
GRANT ALL ON moves TO service_role;

GRANT INSERT, SELECT ON documents TO anon;
GRANT ALL ON documents TO authenticated;
GRANT ALL ON documents TO service_role;

GRANT SELECT ON admin_profiles TO authenticated;
GRANT ALL ON admin_profiles TO service_role;

-- Step 6: Create RLS Policies

-- Moves table policies
CREATE POLICY "public_insert_moves"
ON moves FOR INSERT TO anon
WITH CHECK (true);

CREATE POLICY "admin_select_moves"
ON moves FOR SELECT TO authenticated
USING (true);

CREATE POLICY "admin_update_moves"
ON moves FOR UPDATE TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "service_role_all_moves"
ON moves FOR ALL TO service_role
USING (true)
WITH CHECK (true);

-- Documents table policies
CREATE POLICY "public_insert_documents"
ON documents FOR INSERT TO anon
WITH CHECK (true);

CREATE POLICY "admin_select_documents"
ON documents FOR SELECT TO authenticated
USING (true);

CREATE POLICY "admin_all_documents"
ON documents FOR ALL TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "service_role_all_documents"
ON documents FOR ALL TO service_role
USING (true)
WITH CHECK (true);

-- Admin profiles policies
CREATE POLICY "admin_users_select_any_admin"
ON admin_profiles FOR SELECT TO authenticated
USING (true);

-- Step 7: Status Automation Function & Triggers

-- Function to auto-update overall_status when conditions are met
CREATE OR REPLACE FUNCTION check_move_ready()
RETURNS TRIGGER AS $$
BEGIN
  -- Check if all conditions are met for "ready" status
  -- Conditions: all documents complete + permits approved + escort confirmed
  
  -- Check documents completeness
  DECLARE
    doc_record RECORD;
    all_docs_complete BOOLEAN := false;
    all_conditions_met BOOLEAN := false;
  BEGIN
    SELECT * INTO doc_record
    FROM documents
    WHERE move_id = NEW.id;

    IF FOUND THEN
      all_docs_complete := (
        doc_record.insurance_cert = true AND
        doc_record.rateconfirmation = true AND
        doc_record.bill_of_lading = true AND
        doc_record.escort_confirmation = true AND
        doc_record.route_plan = true
      );
    END IF;

    -- Check all conditions
    all_conditions_met := (
      all_docs_complete AND
      NEW.permit_status = 'approved' AND
      NEW.escort_status = 'confirmed'
    );

    -- Auto-update status if conditions met and status isn't already 'ready' or 'in_transit' or 'complete'
    IF all_conditions_met AND NEW.overall_status NOT IN ('ready', 'in_transit', 'complete') THEN
      NEW.overall_status := 'ready';
    END IF;

    -- Auto-update status to 'permits' if documents are complete but permits/escort not ready
    IF all_docs_complete AND NEW.overall_status = 'intake' THEN
      NEW.overall_status := 'permits';
    END IF;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger on moves table (fires on INSERT and UPDATE)
DROP TRIGGER IF EXISTS trg_check_move_ready ON moves;
CREATE TRIGGER trg_check_move_ready
  BEFORE INSERT OR UPDATE ON moves
  FOR EACH ROW
  EXECUTE FUNCTION check_move_ready();

-- Function to check move ready when documents change
CREATE OR REPLACE FUNCTION check_move_ready_on_doc_change()
RETURNS TRIGGER AS $$
DECLARE
  move_record RECORD;
  doc_record RECORD;
  all_docs_complete BOOLEAN := false;
  all_conditions_met BOOLEAN := false;
  target_id BIGINT;
BEGIN
  -- Get the move_id from the document record
  IF TG_OP = 'DELETE' THEN
    target_id := OLD.move_id;
  ELSE
    target_id := NEW.move_id;
  END IF;

  -- Get the move record
  SELECT * INTO move_record FROM moves WHERE id = target_id;
  
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  -- Get all documents for this move (take the first one)
  SELECT * INTO doc_record
  FROM documents
  WHERE move_id = target_id
  LIMIT 1;

  IF FOUND THEN
    all_docs_complete := (
      doc_record.insurance_cert = true AND
      doc_record.rateconfirmation = true AND
      doc_record.bill_of_lading = true AND
      doc_record.escort_confirmation = true AND
      doc_record.route_plan = true
    );
  END IF;

  -- Check all conditions
  all_conditions_met := (
    all_docs_complete AND
    move_record.permit_status = 'approved' AND
    move_record.escort_status = 'confirmed'
  );

  -- Update status if conditions met
  IF all_conditions_met AND move_record.overall_status NOT IN ('ready', 'in_transit', 'complete') THEN
    UPDATE moves
    SET overall_status = 'ready'
    WHERE id = target_id;
  END IF;

  -- Update to 'permits' if docs complete but permits not approved yet
  IF all_docs_complete AND move_record.overall_status = 'intake' THEN
    UPDATE moves
    SET overall_status = 'permits'
    WHERE id = target_id;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Trigger on documents table
DROP TRIGGER IF EXISTS trg_check_move_ready_on_doc_change ON documents;
CREATE TRIGGER trg_check_move_ready_on_doc_change
  AFTER INSERT OR UPDATE OR DELETE ON documents
  FOR EACH ROW
  EXECUTE FUNCTION check_move_ready_on_doc_change();

-- Step 7.5: Enable Realtime publication for live updates
-- This allows the frontend to receive real-time updates via Supabase Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE moves;
ALTER PUBLICATION supabase_realtime ADD TABLE documents;

-- IMPORTANT: You must also enable Realtime in Supabase Dashboard:
-- 1. Go to Database → Replication → Enable Realtime for 'moves' and 'documents' tables
-- 2. Toggle ON both tables under "Available Tables" section
-- 3. This enables Supabase to broadcast changes to connected clients

-- Step 8: Seed Data (Realistic Heavy Haul Loads)

INSERT INTO moves (customer_name, origin, destination, width, height, weight, states_crossed, delivery_date, permit_status, escort_status, overall_status) VALUES
('ABC Manufacturing', 'Houston, TX', 'Atlanta, GA', 14.5, 12.0, 85000, 3, '2026-04-20', 'pending', 'scheduled', 'permits'),
('Steel Dynamics', 'Pittsburgh, PA', 'Chicago, IL', 10.0, 10.5, 62000, 2, '2026-04-15', 'approved', 'confirmed', 'ready'),
('Heavy Lift Co', 'Denver, CO', 'Phoenix, AZ', 16.0, 15.0, 120000, 2, '2026-04-18', 'pending', 'not_scheduled', 'intake'),
('Prime Movers', 'Dallas, TX', 'Charlotte, NC', 12.5, 11.0, 75000, 4, '2026-04-22', 'approved', 'scheduled', 'permits'),
('Mammoth Transport', 'Seattle, WA', 'Salt Lake City, UT', 11.0, 10.0, 55000, 2, '2026-04-12', 'approved', 'confirmed', 'in_transit'),
('Overland Freight', 'Miami, FL', 'Nashville, TN', 15.0, 13.5, 95000, 3, '2026-04-25', 'pending', 'not_scheduled', 'intake'),
('Giant Moves Inc', 'Detroit, MI', 'Boston, MA', 13.0, 12.0, 88000, 5, '2026-04-14', 'approved', 'confirmed', 'ready'),
('Superload Systems', 'Los Angeles, CA', 'Las Vegas, NV', 18.0, 16.0, 150000, 2, '2026-04-28', 'pending', 'not_scheduled', 'intake');

-- Create document records for each move
INSERT INTO documents (move_id, insurance_cert, rateconfirmation, bill_of_lading, escort_confirmation, route_plan) VALUES
(1, true, true, false, true, false),
(2, true, true, true, true, true),
(3, false, false, false, false, false),
(4, true, true, true, false, true),
(5, true, true, true, true, true),
(6, false, true, false, false, false),
(7, true, true, true, true, true),
(8, false, false, false, false, false);

-- Step 8: Verification Queries

-- Check tables exist
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename IN ('moves', 'documents', 'admin_profiles') ORDER BY tablename;

-- Check RLS is enabled
SELECT tablename, rowsecurity FROM pg_tables WHERE schemaname = 'public' AND tablename IN ('moves', 'documents', 'admin_profiles');

-- Check all policies
SELECT tablename, policyname, cmd, roles FROM pg_policies WHERE schemaname = 'public' AND tablename IN ('moves', 'documents', 'admin_profiles') ORDER BY tablename, policyname;

-- Count seeded data
SELECT 'moves' as table_name, COUNT(*) as count FROM moves
UNION ALL
SELECT 'documents' as table_name, COUNT(*) as count FROM documents;

-- ============================================
-- MIGRATION COMPLETE
-- ============================================
-- Next Steps:
-- 1. Create admin user in Supabase Auth (Authentication → Users)
-- 2. Add user to admin_profiles table:
--    INSERT INTO admin_profiles (id, email, role)
--    VALUES ('UUID_FROM_SUPABASE_AUTH', 'admin@example.com', 'admin');
-- 3. Test the application!
-- ============================================
